export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  PAYCHECK: '/paycheck',
  SPENDING: '/spending',
  WISHLIST: '/wishlist',
  CALENDAR: '/calendar',
  HISTORY: '/history',
  BUFFER: '/buffer',
  EMERGENCY_FUND: '/emergency-fund',
  SAVINGS_GOALS: '/savings-goals',
  MANAGE: '/manage',
  SUBSCRIPTIONS: '/subscriptions',
  SETTINGS: '/settings',
  LOAN_PAYOFF: '/loan-payoff',
  DEBT_TRACKING: '/debt-tracking',
} as const;
